apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tlfhgnlbz-nodejs
  janus-idp.io/tekton: tlfhgnlbz-nodejs
  backstage.io/kubernetes-id: tlfhgnlbz-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tlfhgnlbz-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
